name       : frei0r
version    : 1.7.0
release    : 8
source     :
    - https://github.com/dyne/frei0r/archive/v1.7.0.tar.gz : 6f7cf95ea2257687cc31db0ed9c9bc0eec152e953d515f346eabec048ed2b29d
license    : GPL-2.0-or-later
component  : multimedia.video
summary    : A large collection of free and portable video plugins
description: |
    Frei0r is a minimalistic plugin API for video effects.
    The main emphasis is on simplicity for an API that will round up the most common video effects into simple filters, sources and mixers that can be controlled by parameters.
    It is our hope that this way these simple effects can be shared between many applications, avoiding their reimplementation by different projects.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gavl)
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
