name       : frei0r
version    : 1.5
release    : 1
source     :
    - https://github.com/dyne/frei0r/archive/v1.5.tar.gz : 4ab58d3c31b418b6d07d99ed41a31ce40b075e0f1a2d690924fab6665f9a95a1
license    : GPL-2.0
component  : multimedia.video
summary    : A large collection of free and portable video plugins
description: |
    Frei0r is a minimalistic plugin API for video effects.
    The main emphasis is on simplicity for an API that will round up the
    most common video effects into simple filters, sources and mixers that
    can be controlled by parameters.
    It is our hope that this way these simple effects can be shared between
    many applications, avoiding their reimplementation by different
    projects.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gavl)
    - pkgconfig(opencv)
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
